title: Aksharma Creative
email: your-email@example.com
description: >-
  The craziest crafty website on the face of the earth.
baseurl: "" 
url: "https://akrishnash.github.io"

# The "Secret Sauce" - Using a powerful remote theme
remote_theme: pages-themes/cayman@v0.2.0 # Or any crazy theme you find!
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
