title: Anurag Sharma
email: sharma.anuragkrishna@gmail.com
description: >-
  Scientist at ISRO | Theoretical Computer Scientist | 
  IIT-Delhi Alumnus | Quantum Networking & Gen AI Expert

# Using a remote theme for high-end styling without complex local setup
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Sophisticated social links
github_username: akrishnash
linkedin_username: anurag-sharma-krishna
